### ISSUE TITLE
您好，请问出现下面的代码是因为什么，谢谢啦

### ISSUE THREAD

**Issue by rizhaogw** [ENDsoft233/xueanquan#1]
SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

**Comment by ENDsoft233** [comment]
请问下您使用的 node 版本是什么呢？
在终端内键入 ```node -v``` 查看返回值

**Comment by rizhaogw** [comment]
感谢您回复，是v14.17.1

**Comment by rizhaogw** [comment]
> 请问下您使用的 node 版本是什么呢？
> 在终端内键入 `node -v` 查看返回值
感谢您回复，是v14.17.1

**Comment by rizhaogw** [comment]
请问是不是因为我是在服务器做的原因

**Comment by ENDsoft233** [comment]
比较好奇 ```internal/modules/``` 是什么文件夹
您是先通过 ```yarn install``` 安装，再通过 ```node index.js``` 启动的吗

**Comment by rizhaogw** [comment]
是的呢，我现在换本地的试试，可能是因为我是直接在服务器运行的问题

**Comment by ENDsoft233** [comment]
您好，我以 ```node wrapSafe``` 为关键词在 Google 上搜索了，我怀疑您的问题可能和这一问题有相似之处：

> [https://stackoverflow.com/questions/59073774/node-js-syntaxerror-invalid-or-unexpected-token](https://stackoverflow.com/questions/59073774/node-js-syntaxerror-invalid-or-unexpected-token)
> Did you copy some unicode characters from word or something?
> try retyping the console.log('hello') Something like this has happened to me before, when I copied some code from a word document.

尝试检查一下您在修改代码文件时是否也带入了部分特殊字符导致 node 无法正常运行呢？

不过该问题抛出的异常是 ```Invalid or unexpected token``` ，和您的 ```Unexpected identifier``` 还是有些不同的。

**Comment by ENDsoft233** [comment]
```Unexpected identifier``` 异常好像是指缺少了右括号，分号的问题，也请一并检查一下。

**Comment by ENDsoft233** [comment]
很久没有收到您的回复，看起来是解决了，有任何问题欢迎 reopen 该 issue。
