### ISSUE TITLE
欢迎使用，您已经填入了 25 个账号，已经填写了管理员 Cookie，请更换 willDo 中的 method 方式开始操作。

### ISSUE THREAD

**Issue by mrlinsr** [ENDsoft233/xueanquan#12]
一直提示这个，还有什么要改的，求求了

**Comment by BH4HPA** [comment]
https://github.com/ENDsoft233/xueanquan/blob/651ddb1c7e0e57836824a9325d910de436f43485/config_template.js#L51-L58

**Comment by mrlinsr** [comment]
这个有看到，但是把let methods = {}改成let methods = {0}或者是把methods.listInfo = 3改成methods.listInfo = 0或者是methods.anquanxuexi都会报错…小白求教…

**Comment by BH4HPA** [comment]
> 请更换 willDo 中的 method 方式

改第 58 行的 `willDo`
