### ISSUE TITLE
关于let methods

### ISSUE THREAD

**Issue by Xiaozhi-z** [ENDsoft233/xueanquan#2]
问一下 这个let methods里面填什么阿..

**Comment by ENDsoft233** [comment]
https://github.com/ENDsoft233/xueanquan/blob/d1bde2f0daced0731496f2d2dcfcecd0c6a8fa5d/index.js#L139
https://github.com/ENDsoft233/xueanquan/blob/d1bde2f0daced0731496f2d2dcfcecd0c6a8fa5d/config_template.js#L41

这两处是我预设的。

https://github.com/ENDsoft233/xueanquan/blob/d1bde2f0daced0731496f2d2dcfcecd0c6a8fa5d/config_template.js#L47

您只需要修改这里就可以了，保留 `let willDo = methods.` ，您的 IDE 应该会提示您进行自动补全，或者您可以手动接上 `anquanxuexi` `zhuantihuodong` `jiaqihuodong` 这三个操作。

**Comment by ENDsoft233** [comment]
很久没有收到您的回复，有任何问题欢迎 reopen 该 issue。

**Comment by Xiaozhi-z** [comment]
感谢！
