### ISSUE TITLE
SyntaxError: Unexpected identifier    错误信息，实在是搞不定了。

### ISSUE THREAD

**Issue by shewa7** [ENDsoft233/xueanquan#4]
C:\Users\86153\xueanquan\index.js:31
SyntaxError: Unexpected identifier
[90m    at wrapSafe (internal/modules/cjs/loader.js:1001:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1049:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:950:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:12)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m

**Comment by ENDsoft233** [comment]
出错的地方在赋值管理员 `Cookie` 的地方，请检查是否带入了可能不可见的特殊字符或中文。
另外注意到您本地的代码版本和目前仓库的不太一样，请升级后再尝试。

**Comment by shewa7** [comment]
> 出错的地方在笔记本管理员`Cookie`的地方，请检查是否带入了可能看不到的特殊字符或中文 。
非常感谢回复，已查清楚问题，因为用chrome浏览器查出的cookie有特殊符号并且无用数据多，所以老是报错，用IE和Firefox查出的cookie没问题。这个程序解决我了工作中的大问题，再次感谢您。

**Comment by ENDsoft233** [comment]
好的，很高兴能帮助到您，如果对本项目还有任何问题，欢迎 reopen 该 issue 或者新建 issue。
